name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install Dependencies
      run: |
        cd src
        npm install

    - name: Deploy to EC2
      env:
        EC2_HOST: ${{ secrets.EC2_PUBLIC_IP }}
        EC2_USER: ubuntu
        SSH_KEY: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
      run: |
        ssh -i <(echo "$SSH_KEY") -o StrictHostKeyChecking=no $EC2_USER@$EC2_HOST "cd ~/Cloud-Based-CI-CD-Pipeline- && git pull && cd src && npm install && pm2 restart app || pm2 start app.js --name app"
